USE [Animedata_dev]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_RESOURC__RESOU__0B27A5C0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_RESOURCE_TBL] DROP CONSTRAINT [DF__T_RESOURC__RESOU__0B27A5C0]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_RESOURC__ENABL__0C1BC9F9]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_RESOURCE_TBL] DROP CONSTRAINT [DF__T_RESOURC__ENABL__0C1BC9F9]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_RESOURC__LAST___0D0FEE32]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_RESOURCE_TBL] DROP CONSTRAINT [DF__T_RESOURC__LAST___0D0FEE32]
END

GO

USE [Animedata_dev]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 08/23/2016 10:54:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_RESOURCE_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_RESOURCE_TBL]
GO

USE [Animedata_dev]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 08/23/2016 10:54:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_RESOURCE_TBL](
	[RESOURCE_ID] [int] NOT NULL,
	[RESOURCE_TYPE_ID] [tinyint] NOT NULL,
	[STORAGE_ID] [tinyint] NOT NULL,
	[RESOURCE_FILEPATH] [nvarchar](1000) NULL,
	[RESOURCE_FILENAME] [nvarchar](1000) NOT NULL,
	[RESOURCE_SUFFIX] [nvarchar](10) NOT NULL,
	[TRACK_BITRATE] [nvarchar](20) NULL,
	[TRACK_LENGTH] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RESOURCE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT ((1)) FOR [RESOURCE_TYPE_ID]
GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT ((1)) FOR [ENABLE_FLG]
GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO


