USE [Animedata_dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_ALBUM_TYPE_MST](
	[ALBUM_TYPE_ID] [smallint] NOT NULL,
	[ALBUM_TYPE_NAME] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_T_ALBUM_TYPE_MST] PRIMARY KEY CLUSTERED 
(
	[ALBUM_TYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_ALBUM_TYPE_MST] ADD  CONSTRAINT [DF_T_ALBUM_TYPE_MST_LAST_UPDATE_DATETIME]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO


