BEGIN TRAN 
--T_ANIME_TBL--
ALTER TABLE ANIMEDATA.dbo.T_ANIME_TBL
ALTER COLUMN STATUS smallint not null

ALTER TABLE ANIMEDATA.dbo.T_ANIME_TBL
ALTER COLUMN ORIGINAL smallint not null

ALTER TABLE ANIMEDATA.dbo.T_ANIME_TBL
ADD MUSIC_STATUS smallint

ALTER TABLE ANIMEDATA.dbo.T_ANIME_TBL
ADD ENABLE_FLG bit NOT NULL DEFAULT 1

ALTER TABLE ANIMEDATA.dbo.T_ANIME_TBL
ADD LAST_UPDATE_DATETIME datetime NOT NULL DEFAULT GETDATE()

--T_CHARACTER_TBL
ALTER TABLE ANIMEDATA.dbo.T_CHARACTER_TBL
ADD ENABLE_FLG bit NOT NULL DEFAULT 1

ALTER TABLE ANIMEDATA.dbo.T_CHARACTER_TBL
ADD LAST_UPDATE_DATETIME datetime NOT NULL DEFAULT GETDATE()

--T_COMPANY_TBL
ALTER TABLE ANIMEDATA.dbo.T_COMPANY_TBL
ADD ENABLE_FLG bit  NOT NULL DEFAULT 1

ALTER TABLE ANIMEDATA.dbo.T_COMPANY_TBL
ADD LAST_UPDATE_DATETIME datetime NOT NULL DEFAULT GETDATE()

--T_CV_TBL
ALTER TABLE ANIMEDATA.dbo.T_CV_TBL
ADD ENABLE_FLG bit  NOT NULL DEFAULT 1

ALTER TABLE ANIMEDATA.dbo.T_CV_TBL
ADD LAST_UPDATE_DATETIME datetime NOT NULL DEFAULT GETDATE()

--T_PLAYINFO_TBL
ALTER TABLE ANIMEDATA.dbo.T_PLAYINFO_TBL
ALTER COLUMN STATUS smallint not null 

ALTER TABLE ANIMEDATA.dbo.T_PLAYINFO_TBL
ADD ENABLE_FLG bit NOT NULL DEFAULT 1

ALTER TABLE ANIMEDATA.dbo.T_PLAYINFO_TBL
ADD LAST_UPDATE_DATETIME datetime NOT NULL DEFAULT GETDATE()

--T_ALBUM_TBL
CREATE TABLE ANIMEDATA.dbo.T_ALBUM_TBL
(
ALBUM_ID   nchar(10) PRIMARY KEY
,ALBUM_ANIME_TYPE   char(1) not null
,ALBUM_INANIME_NO int
,ALBUM_TYPE   smallint NOT NULL
,ALBUM_TITLE_NAME   char(1000) NOT NULL
,TOTAL_DISC_COUNT   smallint NOT NULL
,TOTAL_TRACK_COUNT   smallint NOT NULL
,DESCRIPTION   nvarchar
,ENABLE_FLG   bit not null DEFAULT 1
,LAST_UPDATE_DATETIME   datetime NOT NULL DEFAULT GETDATE()
)

--T_TRACK_TBL
CREATE TABLE ANIMEDATA.dbo.T_TRACK_TBL
(
TRACK_ID   nchar(10) PRIMARY KEY
,P_ALBUM_ID   nchar(10)
,TRACK_TYPE   smallint NOT NULL
,DISC_NO   smallint default 1 NOT NULL
,TRACK_NO   smallint NOT NULL
,TRACK_TITLE_NAME   nvarchar
,ARTIST_ID   nchar(10) not null
,ANIME_NO   nchar(4)
,SALES_YEAR   int
,DESCRIPTION   nvarchar
,ENABLE_FLG   bit NOT NULL DEFAULT 1
,LAST_UPDATE_DATETIME   datetime NOT NULL DEFAULT GETDATE()
)

--T_ARTIST_TBL
CREATE TABLE ANIMEDATA.dbo.T_ARTIST_TBL
(
ARTIST_ID   nchar(10) primary key
,ARTIST_NAME   nvarchar not null
,GENDER_ID   smallint not null
,CHARACTER_FLG bit not null DEFAULT 0
,CHARACTER_LIST nvarchar
,CV_FLG bit not null DEFAULT 0
,CV_LIST nvarchar
,DESCRIPTION   nvarchar
,ENABLE_FLG   bit NOT NULL DEFAULT 1
,LAST_UPDATE_DATETIME   datetime NOT NULL DEFAULT GETDATE()
)

--COMMIT
ROLLBACK

