USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ANIME_TBL]    Script Date: 11/13/2015 17:13:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ANIME_TBL](
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_CHN_NAME] [varchar](255) NOT NULL,
	[ANIME_JPN_NAME] [varchar](255) NOT NULL,
	[ANIME_NN] [varchar](10) NOT NULL,
	[STATUS] [int] NOT NULL,
	[ORIGINAL] [int] NOT NULL,
 CONSTRAINT [PK_T_TBL] PRIMARY KEY CLUSTERED 
(
	[ANIME_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

