USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 11/13/2015 17:14:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [nchar](10) NOT NULL,
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

