USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ANIME_TBL]    Script Date: 11/13/2015 17:13:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ANIME_TBL](
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_CHN_NAME] [varchar](255) NOT NULL,
	[ANIME_JPN_NAME] [varchar](255) NOT NULL,
	[ANIME_NN] [varchar](10) NOT NULL,
	[STATUS] [int] NOT NULL,
	[ORIGINAL] [int] NOT NULL,
 CONSTRAINT [PK_T_TBL] PRIMARY KEY CLUSTERED 
(
	[ANIME_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 11/13/2015 17:13:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CHARACTER_TBL](
	[CHARACTER_NO] [varchar](10) NOT NULL,
	[CHARACTER_NAME] [varchar](255) NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[CV_ID] [int] NOT NULL,
	[LEADING_FLG] [bit] NOT NULL,
 CONSTRAINT [PK_T_CHARACTER_TBL] PRIMARY KEY CLUSTERED 
(
	[CHARACTER_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_CHARACTER_TBL] ADD  CONSTRAINT [DF_T_CHARACTER_TBL_LEADING_FLG]  DEFAULT ((0)) FOR [LEADING_FLG]
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 11/13/2015 17:14:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [nchar](10) NOT NULL,
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 11/13/2015 17:14:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CV_TBL](
	[CV_ID] [int] NOT NULL,
	[CV_NAME] [varchar](255) NOT NULL,
	[CV_GENDER] [char](1) NULL,
	[CV_BIRTH] [date] NULL,
	[CV_OFFICE_ID] [int] NULL,
 CONSTRAINT [PK_T_CV_TBL] PRIMARY KEY CLUSTERED 
(
	[CV_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_PLAYINFO_TBL]    Script Date: 11/13/2015 17:14:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_PLAYINFO_TBL](
	[PLAYINFO_ID] [int] NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_PLAYINFO] [varchar](255) NOT NULL,
	[STATUS] [int] NOT NULL,
	[START_TIME] [date] NULL,
	[WATCH_TIME] [date] NULL,
	[PARTS] [int] NULL,
	[COMPANY_ID] [int] NULL,
 CONSTRAINT [PK_T_PLAYINFO_TBL] PRIMARY KEY CLUSTERED 
(
	[PLAYINFO_ID] ASC,
	[ANIME_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

