USE [ANIMEDATA]
GO

DROP TABLE [dbo].[T_COMPANY_TBL]
/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 2015/11/15 1:08:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [varchar](255) NOT NULL,
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
