USE [ANIMEDATA]
GO

ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] DROP CONSTRAINT [DF__T_TRACK_R__LAST___160F4887]
GO

/****** Object:  Table [dbo].[T_TRACK_RESOURCE_TBL]    Script Date: 2016/2/1 23:16:51 ******/
DROP TABLE [dbo].[T_TRACK_RESOURCE_TBL]
GO

/****** Object:  Table [dbo].[T_TRACK_RESOURCE_TBL]    Script Date: 2016/2/1 23:16:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_TRACK_RESOURCE_TBL](
	[TRACK_ID] [char](10) NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRACK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO


