USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 2016/2/1 23:16:11 ******/
DROP TABLE [dbo].[T_RESOURCE_TBL]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 2016/2/1 23:16:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_RESOURCE_TBL](
	[RESOURCE_ID] [int] IDENTITY(1,1) NOT NULL,
	[RESOURCE_TYPE] [tinyint] NOT NULL DEFAULT ((1)),
	[STORAGE_ID] [tinyint] NULL,
	[RESOURCE_FILEPATH] [nvarchar](1000) NULL,
	[RESOURCE_FILENAME] [nvarchar](1000) NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[RESOURCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


