USE [ANIMEDATA]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___ENABL__2EDAF651]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___ENABL__2EDAF651]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___LAST___2FCF1A8A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___LAST___2FCF1A8A]
END

GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ARTIST_MAPPING_TBL]    Script Date: 02/25/2016 21:11:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_ARTIST_MAPPING_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_ARTIST_MAPPING_TBL]
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ARTIST_MAPPING_TBL]    Script Date: 02/25/2016 21:11:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ARTIST_MAPPING_TBL](
	[ARTIST_ID] [nchar](10) NOT NULL,
	[MAPPING_TYPE] [tinyint] NOT NULL,
	[CHARACTER_ID] [varchar](10) NULL,
	[CVID] [int] NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] ADD  DEFAULT ((1)) FOR [ENABLE_FLG]
GO

ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO


