USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ALBUM_TBL]    Script Date: 2016/2/1 23:14:12 ******/
DROP TABLE [dbo].[T_ALBUM_TBL]
GO

/****** Object:  Table [dbo].[T_ALBUM_TBL]    Script Date: 2016/2/1 23:14:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ALBUM_TBL](
	[ALBUM_ID] [nchar](10) NOT NULL,
	[ALBUM_ANIME_TYPE] [char](1) NOT NULL,
	[ALBUM_INANIME_NO] [int] NULL,
	[ANIME_NO] [nchar](4) NOT NULL,
	[ALBUM_TYPE] [tinyint] NOT NULL,
	[ALBUM_TITLE_NAME] [char](1000) NOT NULL,
	[TOTAL_DISC_COUNT] [smallint] NOT NULL,
	[TOTAL_TRACK_COUNT] [smallint] NOT NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[ALBUM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ANIME_TBL]    Script Date: 2016/2/1 23:13:42 ******/
DROP TABLE [dbo].[T_ANIME_TBL]
GO

/****** Object:  Table [dbo].[T_ANIME_TBL]    Script Date: 2016/2/1 23:13:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ANIME_TBL](
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_CHN_NAME] [varchar](255) NOT NULL,
	[ANIME_JPN_NAME] [varchar](255) NOT NULL,
	[ANIME_NN] [varchar](10) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[ORIGINAL] [smallint] NOT NULL,
	[MUSIC_STATUS] [smallint] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_TBL] PRIMARY KEY CLUSTERED 
(
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ARTIST_TBL]    Script Date: 2016/2/1 23:14:54 ******/
DROP TABLE [dbo].[T_ARTIST_TBL]
GO

/****** Object:  Table [dbo].[T_ARTIST_TBL]    Script Date: 2016/2/1 23:14:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_ARTIST_TBL](
	[ARTIST_ID] [nchar](10) NOT NULL,
	[ARTIST_NAME] [nvarchar](1000) NOT NULL,
	[GENDER_ID] [tinyint] NOT NULL,
	[CHARACTER_FLG] [bit] NOT NULL DEFAULT ((0)),
	[CV_FLG] [bit] NOT NULL DEFAULT ((0)),
	[DESCRIPTION] [nvarchar](1000) NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[ARTIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 2016/2/1 23:15:09 ******/
DROP TABLE [dbo].[T_CHARACTER_TBL]
GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 2016/2/1 23:15:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CHARACTER_TBL](
	[CHARACTER_NO] [varchar](10) NOT NULL,
	[CHARACTER_NAME] [varchar](255) NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[CV_ID] [int] NOT NULL,
	[LEADING_FLG] [bit] NOT NULL CONSTRAINT [DF_T_CHARACTER_TBL_LEADING_FLG]  DEFAULT ((0)),
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CHARACTER_TBL] PRIMARY KEY CLUSTERED 
(
	[CHARACTER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 2016/2/1 23:15:26 ******/
DROP TABLE [dbo].[T_COMPANY_TBL]
GO

/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 2016/2/1 23:15:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [varchar](255) NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/2/1 23:15:40 ******/
DROP TABLE [dbo].[T_CV_TBL]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/2/1 23:15:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CV_TBL](
	[CV_ID] [int] NOT NULL,
	[CV_NAME] [varchar](255) NOT NULL,
	[CV_GENDER] [char](1) NULL,
	[CV_BIRTH] [date] NULL,
	[CV_OFFICE_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CV_TBL] PRIMARY KEY CLUSTERED 
(
	[CV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_PLAYINFO_TBL]    Script Date: 2016/2/1 23:15:57 ******/
DROP TABLE [dbo].[T_PLAYINFO_TBL]
GO

/****** Object:  Table [dbo].[T_PLAYINFO_TBL]    Script Date: 2016/2/1 23:15:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_PLAYINFO_TBL](
	[PLAYINFO_ID] [int] NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_PLAYINFO] [varchar](255) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[START_TIME] [date] NULL,
	[WATCH_TIME] [date] NULL,
	[PARTS] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_PLAYINFO_TBL] PRIMARY KEY CLUSTERED 
(
	[PLAYINFO_ID] ASC,
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 02/26/2016 14:24:01 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_RESOURCE_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_RESOURCE_TBL]
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_RESOURCE_TBL]    Script Date: 02/26/2016 14:24:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_RESOURCE_TBL](
	[RESOURCE_ID] [int] NOT NULL,
	[RESOURCE_TYPE] [tinyint] NOT NULL,
	[STORAGE_ID] [tinyint] NULL,
	[RESOURCE_FILEPATH] [nvarchar](1000) NULL,
	[RESOURCE_FILENAME] [nvarchar](1000) NULL,
	[ENABLE_FLG] [bit] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RESOURCE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT ((1)) FOR [RESOURCE_TYPE]
GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT ((1)) FOR [ENABLE_FLG]
GO

ALTER TABLE [dbo].[T_RESOURCE_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO





USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_STORAGE_MST]    Script Date: 2016/2/1 23:16:39 ******/
DROP TABLE [dbo].[T_STORAGE_MST]
GO

/****** Object:  Table [dbo].[T_STORAGE_MST]    Script Date: 2016/2/1 23:16:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_STORAGE_MST](
	[STORAGE_ID] [int] NOT NULL,
	[STORAGE_PATH] [nvarchar](1000) NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[STORAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [ANIMEDATA]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_TRACK_R__ENABL__3A4CA8FD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] DROP CONSTRAINT [DF__T_TRACK_R__ENABL__3A4CA8FD]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_TRACK_R__LAST___3B40CD36]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] DROP CONSTRAINT [DF__T_TRACK_R__LAST___3B40CD36]
END

GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_TRACK_RESOURCE_TBL]    Script Date: 02/26/2016 14:18:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_TRACK_RESOURCE_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_TRACK_RESOURCE_TBL]
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_TRACK_RESOURCE_TBL]    Script Date: 02/26/2016 14:18:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_TRACK_RESOURCE_TBL](
	[TRACK_ID] [char](10) NOT NULL,
	[RESOURCE_ID] [int] NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRACK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] ADD  DEFAULT ((1)) FOR [ENABLE_FLG]
GO

ALTER TABLE [dbo].[T_TRACK_RESOURCE_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO




USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_TRACK_TBL]    Script Date: 2016/2/1 23:17:05 ******/
DROP TABLE [dbo].[T_TRACK_TBL]
GO

/****** Object:  Table [dbo].[T_TRACK_TBL]    Script Date: 2016/2/1 23:17:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_TRACK_TBL](
	[TRACK_ID] [nchar](10) NOT NULL,
	[P_ALBUM_ID] [nchar](10) NULL,
	[TRACK_TYPE] [smallint] NOT NULL,
	[DISC_NO] [smallint] NOT NULL DEFAULT ((1)),
	[TRACK_NO] [smallint] NOT NULL,
	[TRACK_TITLE_NAME] [nvarchar](1000) NULL,
	[ARTIST_ID] [nchar](10) NOT NULL,
	[ANIME_NO] [nchar](4) NULL,
	[SALES_YEAR] [int] NULL,
	[DESCRIPTION] [nvarchar](1000) NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[TRACK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [ANIMEDATA]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___ENABL__2EDAF651]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___ENABL__2EDAF651]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___LAST___2FCF1A8A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___LAST___2FCF1A8A]
END

GO

USE [ANIMEDATA]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___ENABL__2EDAF651]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___ENABL__2EDAF651]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__T_ARTIST___LAST___2FCF1A8A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] DROP CONSTRAINT [DF__T_ARTIST___LAST___2FCF1A8A]
END

GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ARTIST_MAPPING_TBL]    Script Date: 02/26/2016 11:08:13 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_ARTIST_MAPPING_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_ARTIST_MAPPING_TBL]
GO

USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_ARTIST_MAPPING_TBL]    Script Date: 02/26/2016 11:08:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_ARTIST_MAPPING_TBL](
	[ARTIST_ID] [nchar](10) NOT NULL,
	[MAPPING_TYPE] [tinyint] NOT NULL,
	[CHARACTER_NO] [varchar](10) NULL,
	[CVID] [int] NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] ADD  DEFAULT ((1)) FOR [ENABLE_FLG]
GO

ALTER TABLE [dbo].[T_ARTIST_MAPPING_TBL] ADD  DEFAULT (getdate()) FOR [LAST_UPDATE_DATETIME]
GO


