SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

/****** Object:  DataBase [ANIMEDATA_DEV]    Script Date: 2016/2/1 23:15:09 ******/
IF  EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE name = 'ANIMEDATA_DEV')
DROP DATABASE [ANIMEDATA_DEV]
GO

CREATE DATABASE ANIMEDATA_DEV
GO

USE ANIMEDATA_DEV
GO

/****** Object:  Table [dbo].[T_ANIME_TBL]    Script Date: 2016/2/1 23:15:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_ANIME_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_ANIME_TBL]
GO

CREATE TABLE [dbo].[T_ANIME_TBL](
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_CHN_NAME] [varchar](255) NOT NULL,
	[ANIME_JPN_NAME] [varchar](255) NOT NULL,
	[ANIME_NN] [varchar](10) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[ORIGINAL] [smallint] NOT NULL,
	[MUSIC_STATUS] [smallint] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_TBL] PRIMARY KEY CLUSTERED 
(
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 2016/2/1 23:15:09 ******/

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_CHARACTER_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_CHARACTER_TBL]
GO

CREATE TABLE [dbo].[T_CHARACTER_TBL](
	[CHARACTER_NO] [varchar](10) NOT NULL,
	[CHARACTER_NAME] [varchar](255) NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[CV_ID] [int] NOT NULL,
	[LEADING_FLG] [bit] NOT NULL CONSTRAINT [DF_T_CHARACTER_TBL_LEADING_FLG]  DEFAULT ((0)),
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CHARACTER_TBL] PRIMARY KEY CLUSTERED 
(
	[CHARACTER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[T_COMPANY_TBL]    Script Date: 2016/2/1 23:15:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_COMPANY_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_COMPANY_TBL]
GO

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [varchar](255) NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/2/1 23:15:40 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_CV_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_CV_TBL]
GO

CREATE TABLE [dbo].[T_CV_TBL](
	[CV_ID] [int] NOT NULL,
	[CV_NAME] [varchar](255) NOT NULL,
	[CV_GENDER] [char](1) NULL,
	[CV_BIRTH] [date] NULL,
	[CV_OFFICE_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CV_TBL] PRIMARY KEY CLUSTERED 
(
	[CV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[T_PLAYINFO_TBL]    Script Date: 2016/2/1 23:15:57 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_PLAYINFO_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_PLAYINFO_TBL]
GO

CREATE TABLE [dbo].[T_PLAYINFO_TBL](
	[PLAYINFO_ID] [int] NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_PLAYINFO] [varchar](255) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[START_TIME] [date] NULL,
	[WATCH_TIME] [date] NULL,
	[PARTS] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_PLAYINFO_TBL] PRIMARY KEY CLUSTERED 
(
	[PLAYINFO_ID] ASC,
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO