USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/2/1 23:15:40 ******/
DROP TABLE [dbo].[T_CV_TBL]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/2/1 23:15:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CV_TBL](
	[CV_ID] [int] NOT NULL,
	[CV_NAME] [varchar](255) NOT NULL,
	[CV_GENDER] [char](1) NULL,
	[CV_BIRTH] [date] NULL,
	[CV_OFFICE_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CV_TBL] PRIMARY KEY CLUSTERED 
(
	[CV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


