USE [ANIMEDATA]
GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 2016/2/1 23:15:09 ******/
DROP TABLE [dbo].[T_CHARACTER_TBL]
GO

/****** Object:  Table [dbo].[T_CHARACTER_TBL]    Script Date: 2016/2/1 23:15:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_CHARACTER_TBL](
	[CHARACTER_NO] [varchar](10) NOT NULL,
	[CHARACTER_NAME] [varchar](255) NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[CV_ID] [int] NOT NULL,
	[LEADING_FLG] [bit] NOT NULL CONSTRAINT [DF_T_CHARACTER_TBL_LEADING_FLG]  DEFAULT ((0)),
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CHARACTER_TBL] PRIMARY KEY CLUSTERED 
(
	[CHARACTER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


