USE [Animedata_dev]
GO

/****** Object:  Table [dbo].[T_ARTIST_ID_TBL]    Script Date: 08/05/2016 15:38:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_ARTIST_ID_TBL]') AND type in (N'U'))
DROP TABLE [dbo].[T_ARTIST_ID_TBL]
GO

USE [Animedata_dev]
GO

/****** Object:  Table [dbo].[T_ARTIST_ID_TBL]    Script Date: 08/05/2016 15:38:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_ARTIST_ID_TBL](
	[ARTIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_T_ARTIST_ID_TBL] PRIMARY KEY CLUSTERED 
(
	[ARTIST_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


