create database animedata_dev;

use animedata_dev;

CREATE TABLE T_ANIME_TBL(
	ANIME_NO char(4) NOT NULL primary key,
	ANIME_CHN_NAME varchar(255) NOT NULL,
	ANIME_JPN_NAME varchar(255) NOT NULL,
	ANIME_NN varchar(10) NOT NULL,
	STATUS smallint NOT NULL,
	ORIGINAL smallint NOT NULL,
	MUSIC_STATUS smallint NULL,
	ENABLE_FLG bit NOT NULL DEFAULT 1,
	LAST_UPDATE_DATETIME datetime NOT NULL );
	
CREATE TABLE T_CHARACTER_TBL(
	CHARACTER_NO varchar(10) NOT NULL primary key,
	CHARACTER_NAME varchar(255) NOT NULL,
	ANIME_NO char(4) NOT NULL,
	CV_ID int NOT NULL,
	LEADING_FLG bit NOT NULL  DEFAULT 0,
	ENABLE_FLG bit NOT NULL DEFAULT 1,
	LAST_UPDATE_DATETIME datetime NOT NULL);
	
CREATE TABLE T_CV_TBL(
	CV_ID int NOT NULL primary key,
	CV_NAME varchar(255) NOT NULL,
	CV_GENDER char(1) NULL,
	CV_BIRTH date NULL,
	CV_OFFICE_ID int NULL,
	ENABLE_FLG bit NOT NULL DEFAULT 1,
	LAST_UPDATE_DATETIME datetime NOT NULL );
	
CREATE TABLE T_COMPANY_TBL(
	COMPANY_ID int NOT NULL primary key,
	COMPANY_NAME varchar(255) NOT NULL,
	ENABLE_FLG bit NOT NULL DEFAULT 1,
	LAST_UPDATE_DATETIME datetime NOT NULL );
	
CREATE TABLE T_PLAYINFO_TBL(
	PLAYINFO_ID int NOT NULL,
	ANIME_NO char(4) NOT NULL,
	ANIME_PLAYINFO varchar(255) NOT NULL,
	STATUS smallint NOT NULL,
	START_TIME date NULL,
	WATCH_TIME date NULL,
	PARTS int NULL,
	COMPANY_ID int NULL,
	ENABLE_FLG bit NOT NULL DEFAULT 1,
	LAST_UPDATE_DATETIME datetime NOT NULL ,
	PRIMARY KEY (`PLAYINFO_ID`, `ANIME_NO`));