USE [ANIMEDATA_DEV]
GO

/****** Object:  Table [dbo].[T_STORAGE_MST]    Script Date: 2016/2/1 23:16:39 ******/
DROP TABLE [dbo].[T_STORAGE_MST]
GO

/****** Object:  Table [dbo].[T_STORAGE_MST]    Script Date: 2016/2/1 23:16:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_STORAGE_MST](
	[STORAGE_ID] [int] NOT NULL,
	[STORAGE_PATH] [nvarchar](1000) NULL,
	[DESCRTITION] [nvarchar](1000) NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[STORAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


